---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: nov-28-test-fourdotfour-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nov-28-test-fourdotfour-2 
  name: nov-28-test-fourdotfour-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi