apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nov-28-test-fourdotfour-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/nov-28-test-fourdotfour-2:7133898164533f9b5525634ac2b8b652303f817b@sha256:a1eed26a2131b289dfd9cee6d3c38649599bc1f02732e7c47a5fa539292347d3 # use pre-built to bootstrap 
          name: app-inference
